### ISSUE TITLE
Project requirements

### ISSUE THREAD

**Issue by dnhn** [Infra-Knight/Drugstore#1]
- [x] #4 Show drugs in different categories (vitamins, antibiotic,…)
- [x] #4 List item ordered by attributes with pagination
- [x] #4 Show drug specifications including images and description
- [x] #5 Provide UML
- [x] #2 Provide database
- [x] #7 Add Google Maps
- [x] #2 At least 100 items
- [x] #8 Apply on-page SEO
- [x] #6 Authentication, authorization (check if email exists)
